services:
  - type: web
    name: rize-albums-backend-5001
    runtime: python
    rootDir: 5001
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 2 server:app
    envVars:
      - key: SHOPIFY_STORE_URL
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_API_VERSION
        sync: false
      - key: SHOPIFY_PRODUCT_ID
        sync: false
      - key: SHOPIFY_VARIANT_48
        sync: false
      - key: SHOPIFY_VARIANT_75
        sync: false
      - key: SHOPIFY_VARIANT_96
        sync: false
      - key: SHOPIFY_VARIANT_STAND
        sync: false
      - key: SHOPIFY_VARIANT_MOUNTING
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: BACKEND_URL
        sync: false
    healthCheckPath: /api/prices

